// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/williandandrade/address-validation-service/internal/usecase (interfaces: ValidateAddressUsecaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=validate_address_mock.go -package=usecase github.com/williandandrade/address-validation-service/internal/usecase ValidateAddressUsecaseInterface
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	dto "github.com/williandandrade/address-validation-service/internal/api/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockValidateAddressUsecaseInterface is a mock of ValidateAddressUsecaseInterface interface.
type MockValidateAddressUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidateAddressUsecaseInterfaceMockRecorder
	isgomock struct{}
}

// MockValidateAddressUsecaseInterfaceMockRecorder is the mock recorder for MockValidateAddressUsecaseInterface.
type MockValidateAddressUsecaseInterfaceMockRecorder struct {
	mock *MockValidateAddressUsecaseInterface
}

// NewMockValidateAddressUsecaseInterface creates a new mock instance.
func NewMockValidateAddressUsecaseInterface(ctrl *gomock.Controller) *MockValidateAddressUsecaseInterface {
	mock := &MockValidateAddressUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockValidateAddressUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateAddressUsecaseInterface) EXPECT() *MockValidateAddressUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockValidateAddressUsecaseInterface) Execute(ctx context.Context, input *dto.ValidateRequest) (*dto.ValidateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*dto.ValidateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockValidateAddressUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockValidateAddressUsecaseInterface)(nil).Execute), ctx, input)
}
